# Generated by Django 3.1 on 2021-05-18 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_auto_20210515_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(max_length=200, null=True)),
                ('cost', models.FloatField()),
                ('isfavourite', models.IntegerField(default=0, null=True)),
                ('sostav', models.TextField(blank=True, null=True)),
                ('gram', models.FloatField(blank=True, null=True)),
                ('ccal', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('fats', models.FloatField(blank=True, null=True)),
                ('carbo', models.FloatField(blank=True, null=True)),
                ('costsale', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavouriteItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.regularaccount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='item.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.store')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAdditive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('costfloat', models.FloatField(null=True)),
                ('coststr', models.CharField(blank=True, max_length=200, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='itemcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.itemcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.store'),
        ),
    ]
