# Generated by Django 3.1 on 2021-11-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('pg_result', models.CharField(blank=True, max_length=200, null=True)),
                ('pg_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('pg_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('pg_description', models.CharField(blank=True, max_length=200, null=True)),
                ('pg_salt', models.CharField(blank=True, max_length=200, null=True)),
                ('pg_sig', models.CharField(blank=True, max_length=200, null=True)),
                ('pg_failure_description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
