# Generated by Django 3.1 on 2021-05-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20210518_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='isfavourite',
            field=models.BooleanField(default=False),
        ),
    ]
