# Generated by Django 3.1 on 2021-12-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('item', '0002_paymentitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemwithquantity',
            options={'ordering': ('-id',), 'verbose_name': 'Товар с количеством', 'verbose_name_plural': 'Товары с количеством'},
        ),
        migrations.AlterModelOptions(
            name='modelcart',
            options={'ordering': ('-id',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_store_order', to='user.store'),
        ),
    ]
