# Generated by Django 3.1 on 2021-12-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20211208_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='orderdelivery_cost',
            field=models.IntegerField(default=0),
        ),
    ]
