# Generated by Django 3.1 on 2021-05-18 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0004_auto_20210518_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavouriteitems',
            name='client',
        ),
        migrations.AddField(
            model_name='userfavouriteitems',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
