# Generated by Django 3.1 on 2021-05-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210515_2005'),
        ('item', '0007_auto_20210519_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpostcart',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientforpostcard', to='user.regularaccount'),
        ),
        migrations.AlterField(
            model_name='modelpostcart',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeidforpostcard', to='user.store'),
        ),
    ]
