# Generated by Django 3.1 on 2021-05-20 09:40

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210515_2005'),
        ('item', '0009_removeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.IntegerField(null=True)),
                ('paymentStatus', models.BooleanField(default=False)),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'Новый'), (2, 'Упаковывается'), (3, 'В пути'), (4, 'Доставлено'), (5, 'Отказано')], default=1)),
                ('totalCost', models.FloatField()),
                ('totalCount', models.IntegerField()),
                ('timedelivery', models.CharField(blank=True, max_length=200, null=True)),
                ('quantityappliances', models.FloatField(blank=True, null=True)),
                ('scancode', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('scorepaid', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('reference1', models.CharField(blank=True, max_length=200, null=True)),
                ('reference2', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.modelcart')),
                ('clientId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientId', to='user.regularaccount')),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeId', to='user.store')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemId', to='item.item')),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Idstore', to='user.store')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.modelorder')),
            ],
        ),
    ]
