# Generated by Django 3.1 on 2021-05-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_clientorderitem_modelorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='scoregot',
            field=models.IntegerField(default=0),
        ),
    ]
