# Generated by Django 3.1 on 2021-05-26 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210525_1427'),
        ('item', '0011_modelorder_scoregot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelorder',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='modelorder',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='modelorder',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('numhouse', models.CharField(blank=True, max_length=200, null=True)),
                ('entrance', models.CharField(blank=True, max_length=200, null=True)),
                ('floor', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.regularaccount')),
            ],
        ),
    ]
