# Generated by Django 3.1 on 2021-05-27 09:18

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20210526_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='ordertype',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Доставка'), (2, 'Самовывоз')], default=1),
        ),
    ]
