# Generated by Django 3.1 on 2021-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_modelorder_ordertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='declinereason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
