# Generated by Django 3.1 on 2021-05-27 09:56

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_modelorder_declinereason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelorder',
            name='paymentType',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Наличка'), (2, 'Пейбокс')], default=1),
        ),
    ]
