# Generated by Django 3.1 on 2021-06-18 06:41

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_auto_20210527_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelorder',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Новый'), (2, 'Обрабатывается'), (3, 'В пути'), (4, 'Доставлено'), (5, 'Отменен'), (6, 'Готово'), (7, 'Получен'), (8, 'Прибыл'), (9, 'Отказ клиента')], default=1),
        ),
    ]
