# Generated by Django 3.1 on 2021-06-21 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_auto_20210618_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='isfavourite',
        ),
        migrations.AlterField(
            model_name='userfavouriteitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_items', to='item.item'),
        ),
    ]
