# Generated by Django 3.1 on 2021-06-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_auto_20210621_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpostcart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelpostcart',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
