# Generated by Django 3.1 on 2021-06-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_auto_20210621_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcart',
            name='listitem',
            field=models.ManyToManyField(to='item.ModelPostCart'),
        ),
        migrations.DeleteModel(
            name='ItemWithQuantity',
        ),
    ]
