# Generated by Django 3.1 on 2021-06-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_auto_20210621_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelpostcart',
            name='total',
        ),
    ]
