# Generated by Django 3.1 on 2021-06-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0022_remove_modelpostcart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpostcart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
