# Generated by Django 3.1 on 2021-06-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_auto_20210621_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpostcart',
            name='forfun',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemadditive',
            name='costfloat',
            field=models.FloatField(default=0),
        ),
    ]
