# Generated by Django 3.1 on 2021-06-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0027_auto_20210624_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='taketogether',
            field=models.ManyToManyField(related_name='_item_taketogether_+', to='item.Item'),
        ),
    ]
