# Generated by Django 3.1 on 2021-06-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210624_1906'),
        ('item', '0028_item_taketogether'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='item.modelorder')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ratingstar', verbose_name='звезда')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.store')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_review', to='user.regularaccount')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
