# Generated by Django 3.1 on 2021-06-30 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0029_orderreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelorder',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.modelcart'),
        ),
    ]
