# Generated by Django 3.1 on 2021-06-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0030_auto_20210630_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelorder',
            name='totalCost',
        ),
        migrations.RemoveField(
            model_name='modelorder',
            name='totalCount',
        ),
    ]
