# Generated by Django 3.1 on 2021-06-30 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0031_auto_20210630_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelorder',
            name='clientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelorder',
            name='storeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeId', to=settings.AUTH_USER_MODEL),
        ),
    ]
