# Generated by Django 3.1 on 2021-06-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_store_avgcheck'),
        ('item', '0032_auto_20210630_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelorder',
            name='clientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientId', to='user.regularaccount'),
        ),
        migrations.AlterField(
            model_name='modelorder',
            name='storeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeId', to='user.store'),
        ),
    ]
