# Generated by Django 3.1 on 2021-06-30 11:42

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0033_auto_20210630_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemadditive',
            old_name='costfloat',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='itemadditive',
            name='coststr',
        ),
        migrations.AlterField(
            model_name='modelorder',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Новый'), (2, 'Подтвержден'), (3, 'Отменен'), (4, 'Готово'), (5, 'В пути'), (6, 'Получен'), (7, 'Прибыл'), (8, 'Доставлено'), (9, 'Отказ клиента')], default=1),
        ),
    ]
