# Generated by Django 3.1 on 2021-06-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0034_auto_20210630_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcart',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
