# Generated by Django 3.1 on 2021-07-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0036_auto_20210630_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemadditive',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
