# Generated by Django 3.1 on 2021-07-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0037_itemadditive_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemwithquantity',
            name='additives',
            field=models.ManyToManyField(to='item.ItemAdditive'),
        ),
    ]
