# Generated by Django 3.1 on 2021-07-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0038_itemwithquantity_additives'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='refusereason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
