# Generated by Django 3.1 on 2021-07-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0039_modelorder_refusereason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemwithquantity',
            old_name='additives',
            new_name='addedadditives',
        ),
    ]
