# Generated by Django 3.1 on 2021-07-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0040_auto_20210701_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemadditive',
            name='select',
        ),
    ]
