# Generated by Django 3.1 on 2021-07-02 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0042_saveorderactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveorderactions',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saveorder', to='item.modelorder'),
        ),
    ]
