# Generated by Django 3.1 on 2021-07-02 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_store_avgcheck'),
        ('item', '0043_auto_20210702_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveorderactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saveuser', to='user.regularaccount'),
        ),
    ]
