# Generated by Django 3.1 on 2021-07-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0044_auto_20210702_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveorderactions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
