# Generated by Django 3.1 on 2021-07-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_store_avgcheck'),
        ('item', '0045_saveorderactions_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoregot', models.IntegerField(blank=True, null=True)),
                ('scorepaid', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordersave', to='item.modelorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storesave', to='user.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersave', to='user.regularaccount')),
            ],
        ),
    ]
