# Generated by Django 3.1 on 2021-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0046_scoreactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='reporttotal',
            field=models.IntegerField(default=0),
        ),
    ]
