# Generated by Django 3.1 on 2021-07-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0048_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveorderactions',
            name='changedby',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
