# Generated by Django 3.1 on 2021-07-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20210714_1232'),
        ('item', '0049_saveorderactions_changedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePaymentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(max_length=200)),
                ('totalprice', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_save', to='item.modelorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_payment_save', to='user.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_save', to='user.regularaccount')),
            ],
        ),
    ]
