# Generated by Django 3.1 on 2021-07-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0050_savepaymentaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveorderactions',
            name='prev_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
