# Generated by Django 3.1 on 2021-07-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0051_saveorderactions_prev_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='iscourier',
            field=models.BooleanField(default=False),
        ),
    ]
