# Generated by Django 3.1 on 2021-08-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0052_modelorder_iscourier'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemwithquantity',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modelcart',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
