# Generated by Django 3.1 on 2021-08-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0053_auto_20210823_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemwithquantity',
            name='visibility',
        ),
    ]
