# Generated by Django 3.1 on 2021-08-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0054_remove_itemwithquantity_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemwithquantity',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
