# Generated by Django 3.1 on 2021-08-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0056_auto_20210823_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemwithquantity',
            name='addedadditives',
            field=models.ManyToManyField(to='item.ItemAdditive'),
        ),
    ]
