# Generated by Django 3.1 on 2021-10-11 20:35

from django.db import migrations, models
import images.imggenerate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=images.imggenerate.all_image_file_path)),
            ],
        ),
    ]
