# Generated by Django 3.1 on 2021-06-30 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleimages',
            old_name='item',
            new_name='article',
        ),
    ]
