# Generated by Django 3.1 on 2021-07-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210630_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleimages',
            old_name='image',
            new_name='link',
        ),
        migrations.AddField(
            model_name='articleimages',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
