# Generated by Django 3.1 on 2021-12-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularaccount',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы'),
        ),
    ]
