# Generated by Django 3.1 on 2021-05-11 08:19

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210510_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularaccount',
            options={'verbose_name': 'Обычный пользователь', 'verbose_name_plural': 'Обычные пользователи'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Пользователь'), (1, 'МАГАЗИН')], default=0),
        ),
    ]
