# Generated by Django 3.1 on 2021-05-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210511_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularaccount',
            name='firebase_token',
        ),
    ]
