# Generated by Django 3.1 on 2021-05-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_regularaccount_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularaccount',
            name='score',
        ),
    ]
