# Generated by Django 3.1 on 2021-05-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_regularaccount_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularaccount',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
    ]
