# Generated by Django 3.1 on 2021-05-15 12:55

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_regularaccount_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Пользователь'), (2, 'МАГАЗИН')], default=1),
        ),
        migrations.CreateModel(
            name='UserFavouriteStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='user.store')),
            ],
        ),
    ]
