# Generated by Django 3.1 on 2021-05-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210515_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavouritestore',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='user.regularaccount'),
        ),
    ]
