# Generated by Django 3.1 on 2021-05-15 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userfavouritestore_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavouritestore',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
