# Generated by Django 3.1 on 2021-05-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210515_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularaccount',
            name='device_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
