# Generated by Django 3.1 on 2021-06-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_withdrawscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='rating',
        ),
    ]
