# Generated by Django 3.1 on 2021-06-21 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_store_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='isfavouritestore',
        ),
        migrations.AlterField(
            model_name='userfavouritestore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_store', to='user.store'),
        ),
    ]
