# Generated by Django 3.1 on 2021-06-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210624_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='avgcheck',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
