# Generated by Django 3.1 on 2021-07-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_store_avgcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularaccount',
            name='datebirth',
            field=models.DateField(blank=True, null=True, verbose_name='День рождение'),
        ),
    ]
