# Generated by Django 3.1 on 2021-07-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210705_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='storeaddress',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
