# Generated by Django 3.1 on 2021-07-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20210713_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='storeaddress',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
