# Generated by Django 3.1 on 2021-07-14 05:59

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20210713_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', django_fsm.FSMIntegerField(choices=[(1, 'Пользователь'), (2, 'МАГАЗИН'), (3, 'Админ')])),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
