# Generated by Django 3.1 on 2021-07-14 06:32

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_appprompt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutApp',
        ),
        migrations.DeleteModel(
            name='DeliveryInfo',
        ),
        migrations.DeleteModel(
            name='ForBusiness',
        ),
        migrations.DeleteModel(
            name='HelpUser',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='PaymentMethodInfo',
        ),
        migrations.DeleteModel(
            name='UserAgreement',
        ),
        migrations.AlterField(
            model_name='appprompt',
            name='type',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Способ оплаты'), (2, 'Способ доставки'), (3, 'Пользовательское соглашение'), (4, 'Оферта'), (5, 'О приложении'), (6, 'Для бизнеса')]),
        ),
    ]
